<?xml version="1.0" encoding="utf-8"?><Database Name="DB_XEKHACH" Class="Data_BanVeXeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-2FGDGJI\SQLEXPRESS;Initial Catalog=DB_XEKHACH;Integrated Security=True" SettingsObjectName="DAL_BanVeXe.Properties.Settings" SettingsPropertyName="DB_XEKHACHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHUYENDI" Member="CHUYENDIs">
    <Type Name="CHUYENDI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_TUYENDI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_XE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TAIXE1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TAIXE2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_PHUXE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOIGIANKHOIHANH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_VE" Member="CT_VEs">
    <Type Name="CT_VE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_VE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_GHE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_KHACHHANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TUYENDI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_CHUYENDI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_DIADIEMLX" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DIADIEMLENXE" Member="DIADIEMLENXEs">
    <Type Name="DIADIEMLENXE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_TUYENDI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDD" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GHE" Member="GHEs">
    <Type Name="GHE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_LOAIXE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENGHE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HOTENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="YKIENDANHGIA" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAINHANVIEN" Member="LOAINHANVIENs">
    <Type Name="LOAINHANVIEN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENLOAINV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIXE" Member="LOAIXEs">
    <Type Name="LOAIXE">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENLOAIXE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOCHONGOI" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_LOAINV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOTENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NOIDEN" Member="NOIDENs">
    <Type Name="NOIDEN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNOIDEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NOIDI" Member="NOIDIs">
    <Type Name="NOIDI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNOIDI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHUXE" Member="PHUXEs">
    <Type Name="PHUXE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_LOAINV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOTENPX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TUYENDI" Member="TUYENDIs">
    <Type Name="TUYENDI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_NOIDI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_NOIDEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_LOAIXE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENTUYEN" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KHOANGCACH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SOGIOCHAY" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIXE" Member="TAIXEs">
    <Type Name="TAIXE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_LOAINV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOTENTX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VE" Member="VEs">
    <Type Name="VE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.XE" Member="XEs">
    <Type Name="XE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_LOAIXE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BIENSO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>